apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gin-demo-deployment
spec:
  selector:
    matchLabels:
      app: gin-demo-label
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: gin-demo-label
        tier: frontend
    spec:
      containers:
      - name: gin-demo
        image: gcr.io/foggy-forge/gin-demo:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        #env:
        #- name: GET_HOSTS_FROM
        #  value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 8080
        - containerPort: 8181

